default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: db
  port: 5432

development:
  <<: *default
  database: samplerails_development

test:
  <<: *default
  database: samplerails_test

production:
  <<: *default
  database: samplerails_production
